"""A2 NLP — rule-based structuring for consultation triage."""

from __future__ import annotations

from pathlib import Path

from src.contracts import A12Result, validate_a12

from .extractors import classify_report, extract_location, extract_time


def infer(path: str | Path, transcricao: str | None = None) -> A12Result:
    """
    Structure an A1 transcription using deterministic NLP rules.

    Args:
        path:
            Audio path kept for compatibility with the existing A1/A2 pipeline.
        transcricao:
            Text generated by A1. When absent, an empty string is processed.

    Returns:
        A validated A1/A2 contract.
    """
    _ = Path(path)
    text = transcricao or ""

    result: A12Result = {
        "transcricao": text,
        "tipo_relato": classify_report(text),
        "local": extract_location(text),
        "tempo": extract_time(text),
    }

    return validate_a12(result)


__all__ = ["infer"]